# Generated by Django 3.2.20 on 2023-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='tour_images/'),
        ),
    ]
